# Generated by Django 6.0.4 on 2026-04-13 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(verbose_name='Код решения')),
                ('status', models.CharField(choices=[('pending', 'На проверке'), ('accepted', 'Принято'), ('wrong', 'Неверно'), ('error', 'Ошибка выполнения'), ('timeout', 'Превышено время')], default='pending', max_length=20, verbose_name='Статус')),
                ('test_results', models.JSONField(default=list, verbose_name='Результаты тестов')),
                ('error_message', models.TextField(blank=True, verbose_name='Сообщение об ошибке')),
                ('time_spent', models.IntegerField(default=0, verbose_name='Время выполнения (сек)')),
                ('used_hint', models.BooleanField(default=False, verbose_name='Использовал подсказку')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='learning.task')),
            ],
            options={
                'verbose_name': 'Решение',
                'verbose_name_plural': 'Решения',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
