# Generated by Django 5.2.14 on 2026-05-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='max_hint_level',
            field=models.IntegerField(default=0, verbose_name='Макс. уровень подсказки'),
        ),
    ]
