# Generated by Django 6.0.4 on 2026-04-25 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theory', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='learning.theory')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('option_a', models.CharField(max_length=400, verbose_name='Вариант A')),
                ('option_b', models.CharField(max_length=400, verbose_name='Вариант B')),
                ('option_c', models.CharField(max_length=400, verbose_name='Вариант C')),
                ('option_d', models.CharField(max_length=400, verbose_name='Вариант D')),
                ('correct', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], max_length=1, verbose_name='Правильный ответ')),
                ('explanation', models.TextField(blank=True, verbose_name='Пояснение')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='learning.quiz')),
            ],
            options={
                'verbose_name': 'Вопрос теста',
                'verbose_name_plural': 'Вопросы теста',
                'ordering': ['order'],
            },
        ),
    ]
