# Generated by Django 6.0.4 on 2026-05-07 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_tag_task_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MiniTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Условие (markdown)')),
                ('starter_code', models.TextField(blank=True, verbose_name='Начальный код')),
                ('test_cases', models.JSONField(default=list, verbose_name='Тест-кейсы')),
                ('hint', models.TextField(blank=True, verbose_name='Подсказка')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('theory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mini_tasks', to='learning.theory')),
            ],
            options={
                'verbose_name': 'Мини-задание',
                'verbose_name_plural': 'Мини-задания',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TheoryProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mini_tasks_passed', models.JSONField(default=list, verbose_name='Сданные мини-задания')),
                ('quiz_score', models.IntegerField(default=0, verbose_name='Правильных ответов')),
                ('quiz_total', models.IntegerField(default=0, verbose_name='Всего вопросов')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('theory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='learning.theory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theory_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Прогресс по теории',
                'verbose_name_plural': 'Прогресс по теориям',
                'unique_together': {('user', 'theory')},
            },
        ),
    ]
