# Generated by Django 6.0.4 on 2026-05-14 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_task_parent_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='concepts',
            field=models.TextField(blank=True, verbose_name='Ключевые концепции'),
        ),
    ]
