# Generated by Django 6.0.4 on 2026-05-15 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0007_module_concepts'),
    ]

    operations = [
        migrations.AddField(
            model_name='minitask',
            name='forbidden_patterns',
            field=models.JSONField(blank=True, default=list, verbose_name='Запрещённые паттерны кода'),
        ),
        migrations.AddField(
            model_name='minitask',
            name='required_patterns',
            field=models.JSONField(blank=True, default=list, verbose_name='Обязательные паттерны кода'),
        ),
    ]
