# Generated by Django 5.2.14 on 2026-05-20 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0008_minitask_forbidden_patterns_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprogress',
            name='current_difficulty',
        ),
    ]
