# Generated by Django 5.2.14 on 2026-05-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0009_remove_userprogress_current_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='theoryprogress',
            name='points_awarded',
            field=models.BooleanField(default=False, verbose_name='Поинт начислен'),
        ),
    ]
