# Generated by Django 6.0.4 on 2026-04-13 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HintRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.TextField(blank=True, verbose_name='Код пользователя')),
                ('hint_text', models.TextField(verbose_name='Сгенерированная подсказка')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Запрос подсказки',
                'verbose_name_plural': 'Запросы подсказок',
            },
        ),
    ]
