# Generated by Django 6.0.4 on 2026-04-13 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assistant', '0001_initial'),
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hintrequest',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hint_requests', to='learning.task'),
        ),
    ]
